### ISSUE TITLE
Capture frame/snapshot/screenshot and export video frames improvements

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#1908]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

- [x] choose JPEG quality #1141
- [ ] Choose output bit depth e.g. 24bit images instead of 48bit #1896
- [ ] JPGXL or AVIF format options for video snapshots #1907
- [ ] Keep selected rotation #823
- [ ] Lossy PNG optimization #1365

**Comment by JNorman-hull** [comment]
![image](https://github.com/user-attachments/assets/4bcc4121-4e81-41f9-a493-7394070fd03e)
![image](https://github.com/user-attachments/assets/4e46b070-cef0-4590-826a-e8f6a6fbebe7)
![image](https://github.com/user-attachments/assets/576c8035-0207-4e4f-a78b-bc6f0e9e96cc)
![image](https://github.com/user-attachments/assets/c44eacec-6e87-4742-83ba-4e314548a093)

The 'File names of extracted video frames' doesn't provide the Frame number when the option is selected and the Frame timestamp seems to persists instead.
I think the intention is that the filenames should be amended with 200 and 300 in this example, not 03.333 and 05.000.

**Comment by mifi** [comment]
which version are you running? for me it works correctly and respects the setting:

<img width="176" alt="Screenshot 2024-10-09 at 11 31 55" src="https://github.com/user-attachments/assets/8817a5e9-11c6-45a0-82d6-47cc99f28799">

does it have the same behaviour regardless of the setting's value?

**Comment by JNorman-hull** [comment]
I am using version 3.61.1.

Yes, it does have the same behaviour regardless of the settings value.

Many thanks,
                                                                                                                                                           .
Dr Josh Norman  (he/him)

Post Doctoral Research Assistant
Hull International Fisheries Institute, School of Natural Sciences

07883102630  |  ORCID<https://orcid.org/0000-0002-2440-3803>  |  Twitter<https://x.com/_JoshNorman>

My standard working hours are 08:45 - 17:00. I am unlikely to  respond outside of this.  In my absence, you can contact HIFI Staff at ***@***.******@***.***>

***@***.***
