### ISSUE TITLE
Merge improvements

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#210]
- [x] Allow changing output format
- [x] Add a progress bar or pop out page that shows when Lossless Cut is merging files.
- [x] Allow retry if failed (don't lose data)
- [ ] Some kind of preview #253
- [ ] Maybe combine with cut functionality so the the user can drag-drop additional segments into the timeline to include. #976 
- [x] Use natural language sorting, see #844
