### ISSUE TITLE
Different output/working directory/folder for different kinds of generated files

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#2115]
Currently LosslessCut allows saving output, temp files and project file all together, either:
- in the same folder as the input file
- or in a custom working directory (selectable by the user)

Some people have asked for more granularity:

- [ ] Allow storing project files in a separate folder #1536
- [ ] Allow storing temporary files (e.g. temporary pre-merge segments) in a separate folder (because sometimes writing them to the working directory is slow if it's not an SSD) #2112 #2382 (somewhat related: #963)
- [ ] Next to media file but in a subfolder #2610

Other improvements:
- [x] Allow changing or toggling between output folders #2101 #2755

**Comment by klaernie** [comment]
I would also like to ask for another option than the mentioned two: relative to the input file, but in a subfolder.

Ideally I would like the project file (the `.llc`) to be stored next to the input file, which then can store were the temporary files were put to (e.g. a `llc-temp` subfolder in the same directory as the input file) and where the outputs went to (like `llc-output`). This way I could quickly reopen a project and easily tell what files were input and which were generated and can be thrown out in a month, while not accidentally deleting the output files.

Maybe I get the time to look at implementing this myself.

**Comment by sardinhunt** [comment]
I agree that working on a fast SSD helps a lot—personally, I manage by organizing and moving files onto the SSD before editing and keeping my main drive spacious. But the lack of output folder favorites (as discussed in https://github.com/mifi/lossless-cut/issues/2101) remains a real workflow issue.

I currently run a helper script that watches the LosslessCut folder and asks where to move files. I’m now building a “don’t ask again” toggle so it just moves clips to a default folder unless changed—basically solving this with extra steps.

It’d be much cleaner if LosslessCut supported a favorite output paths natively. If that helps, I’d be happy to offer €100 to help prioritize this feature in the next 2–3 months—if that’s something you're open to. Maybe it could encourage more incentive-driven donations too.

I know it isn't much but I was hoping someone else saw the value in this feature and contributed.
