### ISSUE TITLE
Keyboard shortcuts and workflow

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#254]
I want this issue to be a place where we can vote and discuss which functions shall be bound to keyboard shortcuts. You can leave an upvote on the shortcuts/functions you want the most.

**Comment by mifi** [comment]
Currently implemented shortcuts:

<kbd>H</kbd> Show/hide help screen
<kbd>SPACE</kbd>, <kbd>k</kbd> Play/pause
<kbd>J</kbd> Slow down video
<kbd>L</kbd> Speed up video
<kbd>←</kbd> Seek backward 1 sec
<kbd>→</kbd> Seek forward 1 sec
<kbd>.</kbd> (period) Tiny seek forward (1/60 sec)
<kbd>,</kbd> (comma) Tiny seek backward (1/60 sec)
<kbd>I</kbd> Mark in / cut start point
<kbd>O</kbd> Mark out / cut end point
<kbd>E</kbd> Cut (export selection in the same directory)
<kbd>C</kbd> Capture snapshot (in the same directory)
<kbd>+</kbd> Add cut segment
<kbd>BACKSPACE</kbd> Remove current cut segment
<kbd>D</kbd> Delete source file

Another alternative is that I could create a custom per-user key shortcut-to-action mapping, but it involves more work.

**Comment by mifi** [comment]
Being able to change the seek time from 1 sec or 1/60 sec somehow, maybe with a modifier key, or use an exponential acceleration when repeatedly pressing a key.

**Comment by mifi** [comment]
Being able to change the seek time from 1 sec or 1/60 sec by using arrow-keys in combination with shift/ctrl/alt for different speeds (speed parameter in seconds adjustable for each combination)

**Comment by mifi** [comment]
👀Seek to next/prev keyframe

**Comment by mifi** [comment]
👀Jump to next/prev segment

**Comment by mifi** [comment]
👀Zoom in/out

**Comment by alsab200** [comment]
Keyboard Shortcuts: I dont know if its already included but frame by frame would be very helpful..
Best implementation is in Potplayer, my experience, f for Forward d for backwards..
To me most important thing is if you press f key continously playback would be like slowmotion and flawless.. More importantly frame-BACK dont work in most of the most known video players.. You can try, with mp4 files especially, it works "flawlessly"
If you can achieve it here would be great..
Also thank you for implementing our suggestion for saving the project..

**Comment by alsab200** [comment]
Excuse if tis is not the right place, but since I started here..
1) FYI Appending a second file doesnt work as with ver. 3.8.0.. It doesnt show up..
Enhancement:
1) Segments list panel at the right.. It takes too much space; it would be best to be able to turn it ON or OFF just like the left panel for tracks..
2) also an option to strip everything (may be when implementing Full Screen View) and leave only timelime line showing segments to make the video display as large as possible..
3) When exporting segments-files.. include label name if any in the file name ..
4) If you use the space key to pause or to start the playback is not smooth.. Seems like there is some jump.. 
Thank you very much for a great program again and wish the best

**Comment by mifi** [comment]
> Keyboard Shortcuts: I dont know if its already included but frame by frame would be very helpful..

Frame stepping is implemented. use <kbd>,</kbd> and <kbd>.</kbd>



> 1. FYI Appending a second file doesnt work as with ver. 3.8.0.. It doesnt show up..

The audio/video tracks don't show up in the track selector? What file are you trying to add? Btw appending files in the time domain is not supported, only including tracks.



> * Segments list panel at the right.. It takes too much space; it would be best to be able to turn it ON or OFF just like the left panel for tracks..

Have added a toggle button.

> * When exporting segments-files.. include label name if any in the file name ..

This has now been implemented

> 5\. If you use the space key to pause or to start the playback is not smooth.. Seems like there is some jump..

I have now improved performance in the newest prerelease version.

**Comment by Fujosej** [comment]
Hi there , love LC.
I tried latest 3.11.0 release and here are some thoughts.

-It would be nice if i can change the amount i wanna scrub/seek with my mouse scroll , right now it scrubs/seeks for 6+ seconds and thats it.

-There is also a bug i think with mouse scroll , when i zoom in using ctrl + mouse scroll , regular scrub/seek with mouse scroll no longer works after that, only if i set it to zoom 1x.

-About paning the timeline , i think an automatic pan would be really nice if its possible , right now when i am zoomed in , it gets stuck in one place and i dont have mouse scroll left / right binds. The only solution is to change zoom level and it snaps back to playhead.

![image](https://user-images.githubusercontent.com/37980944/75544675-8cc97180-5a35-11ea-8e24-387b65d9b5cc.png)
-It's nice , but in my case i need a setting to change my arrow keys to 1/5/10 sec seek.


-Jump to cut start / Jump to cut end, need a hotkeys , or a custom one , every user should be able to set it to whatever they want. 

-Another insteresting addition would be a bind to toggle back to zoom 1x and whatever zoom you were in.

I think ultimately , there has to be a rebind feature for every user to change their hotkeys to whatever they are comfortable with.

**Comment by mifi** [comment]
> -It would be nice if i can change the amount i wanna scrub/seek with my mouse scroll , right now it scrubs/seeks for 6+ seconds and thats it.

I will have to look into this. On my mac when using trackpad, it seeks very smoothly. I think this is an issue on non Macs.

> -There is also a bug i think with mouse scroll , when i zoom in using ctrl + mouse scroll , regular scrub/seek with mouse scroll no longer works after that, only if i set it to zoom 1x.

I think this is also an issue on windows/linux when there is no left/right mouse wheel or trackpad. because on mac I can scroll horizontally and it lets me scroll the timeline when zoomed in. I have to find a solution for this, but for now it seems to work if you <kbd>SHIFT</kbd>+wheel, because then Windows will convert the vertical mouse wheel events to horizontal events

> -Jump to cut start / Jump to cut end, need a hotkeys , or a custom one , every user should be able to set it to whatever they want.

I have changed back to 1 sec seek and with 1% seek at current zoom when holding <kbd>CTRL</kbd>

> -Another insteresting addition would be a bind to toggle back to zoom 1x and whatever zoom you were in.

Have added a similar feature where Z toggle zoom between 1 and a "comfortable zoom level" which is defined as a 100 seconds window

**Comment by mifi** [comment]
> -About paning the timeline , i think an automatic pan would be really nice if its possible , right now when i am zoomed in , it gets stuck in one place and i dont have mouse scroll left / right binds. The only solution is to change zoom level and it snaps back to playhead.

this one is now implemented

**Comment by davidp57** [comment]
First, thanks a lot for this excellent tool that is very efficient !

I don't know if it's been said elsewhere, but I found disturbing that after having pressed L a few times to increase playback speed (btw it works perfectly, and does not stutter at all, not like in Adobe Premiere :+1: ), when I press K two times it does not go back to playing at 100% speed.
Not sure that I am clear, so let me try another way : 
Expected : L L L L L L (500% speed) K (pause) K (100% speed)
Actual : Expected : L L L L L L (500% speed) K (pause) K (500% speed)

Again, thanks !

**Comment by mifi** [comment]
@davidp57  is this how it usually works in other software? (remember speed after pressing `k`)

**Comment by mifi** [comment]
Requested key shortcut: Change rotation (See #334)

**Comment by fedorvinogradov** [comment]
It would be great to have a shortcut not only for selecting cuts (up/down arrows) but also for jumping to these cuts' edges (starting/ending) with the frame seeker (don't know how to call that thing). Maybe with CTRL+up / CTRL+down ?

**Comment by tarve** [comment]
Please add shortcut key for rotation

**Comment by mifi** [comment]
I have added <kbd>R</kbd> for changing rotation

**Comment by mifi** [comment]
- [ ] Requested: Order segments by start time shortcut

**Comment by mifi** [comment]
- [ ] Requested: Jumping to cut start/end

**Comment by tarve** [comment]
> I have added R for changing rotation

Thanks a lot.

**Comment by mifi** [comment]
- [ ] Separate Pause and Play shortcuts. The standard "toggle" play/pause shortcut is always useful of course, so I'm not talking about replacing that - just adding new shortcuts to specifically start or stop. #570

**Comment by markusd1984** [comment]
> Long backwards jump	key-jump-long	Alt-Ctrl-Left
> Long forward jump	key-jump+long	Alt-Ctrl-Right
> ```
> 
> Update: now left/right will jump 1 sec while ctrl/cmd+left/right will jump 1% of the timeline at the current Zoom. alt + left/right will jump to next/prev keyframe

**CTRL+ALT to jump frames**
[Because using arrow keys feels more native to use for frame by frame moves](https://github.com/mifi/lossless-cut/issues/604#issuecomment-767496487) when we have all the other modifier keys combination for jump moves with arrows and since CTRL+ALT is not used anymore 😄 thanks.

**Comment by markusd1984** [comment]
**SHIFT+L/R cycle through all segments cuts**
ideally [SHIFT+L/R cycle through all segments cuts,](https://github.com/mifi/lossless-cut/issues/604#issuecomment-767496487) not just the selected one, that would be great, thanks.

**Comment by mifi** [comment]
Some editing software (not as much as with the J-K-L navigation, see #652) use

CTRL + J Key: Delete everything from before current position, this is currently SHORTCUT I
CTRL + K Key: Cut (Split) at current position, this is currently SHORTCUT B
CTRL + L Key: Delete everything from after current position, this is currently SHORTCUT O
The combination of both navigation and edit using the same keys (only differing by a qualifier key) result in faster navigation/editing - once your brain has connected the wires ;-)

Note: Please do not remove SHORTCUT I and O, these are also pretty common and you should not break the UX of I/O'ers.

From https://github.com/mifi/lossless-cut/issues/653#issue-807987097

**Comment by mifi** [comment]
- [ ] Jump to start of timeline, Ctrl + Home is a standard Windows command to do this in many programs.

**Comment by markusd1984** [comment]
Just realised i meant L/R as in Left/Right arrows in combination with Shift :)

**Comment by 1024mb** [comment]
I think no shortcut should be using the ALT key or make it so the app doesn't use the `ALT` key to focus to the menu bar. There have been a lot of times where I'm browsing the video through the keyboard and I'm jumping between frames using `ALT + ->` or `ALT + <-` and sometimes I just mistake or simply don't want to jump to other frame anymore and only press the `ALT` key and instead of being able to keep browsing with the keyboard the app focuses to the menus and I have to click on the video or somewhere else to keep using the keyboard to control the app.

**Comment by scrool** [comment]
Please add a keyboard shortcut for "Label a segment".

**Comment by mattack1** [comment]
I haven't used the speedup feature (since most of the files I edit are MPEG2 that it doesn't support natively), but I definitely would WANT it to remember after pausing..

**Comment by mifi** [comment]
> Please add a keyboard shortcut for "Label a segment".

already implemented: <kbd>Return</kbd>

**Comment by mifi** [comment]
From https://github.com/mifi/lossless-cut/issues/723#issuecomment-821840162 :
- [ ] Add keyboard shortcut for "Include ONLY this segment in export", e.g. only currently selected segment, because some people often want to export only current segment and would like to not click a menu every time.

**Comment by scrool** [comment]
> > Please add a keyboard shortcut for "Label a segment".
> 
> already implemented: Return

Nice! I'm having trouble to find it in keyboard shortcuts section of integrated help. I'm using version 3.29.0 from FlatHub.

**Comment by taozi1996** [comment]
M:add label to label segment(mark)
Import project
ctrl+1:Losslesscut(csv)
ctrl+2:EDL(MPlayer)
ctrl+3:Text chapters/youtube
ctrl+4:Davinci resolve/final cut pro xml
ctrl+5:Cue sheet file
ctrl+6:Potplayer bookmarks(.pbf)

**Comment by mifi** [comment]
From #570:

- Playback 2x, 3x, 4x, etc., up to whatever max speed makes sense. Honestly, anything over, say 6x is probably overkill for LC, but whatever works.
- Separate Pause and Play shortcuts. The standard "toggle" play/pause shortcut is always useful of course, so I'm not talking about replacing that - just adding new shortcuts to specifically start or stop.

**Comment by mifi** [comment]
From #553: Allow modifier keys when using scroll on timeline for rougher jumps/finer control

**Comment by mifi** [comment]
from email:
> I came with idea for feature that would speedup cutting dramaticaly.
When we set, start or end cut, we do it at current video position. But usually when going through video, we go very fast and miss the correct position. So we have to go back few seconds every time.
If we could set start/end cut 3 or 4 seconds back from current position, we would not have to jump back.

**Comment by mifi** [comment]
have now implemented dynamic keyboard mapping as well as many new assignable actions. WIll be out in the next version:

<img width="518" alt="Screenshot 2022-02-20 at 18 37 40" src="https://user-images.githubusercontent.com/402547/154838613-27fb7a05-4e4b-4627-8af8-d152c252c364.png">

Assignable shortcuts so far:
```
Show/hide help screen
Play/pause
Play/pause (no reset speed)
Speed up playback
Slow down playback
Speed up playback more
Slow down playback more
Step backward 1 frame
Step forward 1 frame
Seek backward 1 sec
Seek forward 1 sec
Seek backward 1% of timeline at current zoom
Seek forward 1% of timeline at current zoom
Jump to cut start
Jump to cut end
Jump to start of video
Jump to end of video
Seek to timecode
Add cut segment
Remove current segment
Mark in / cut start point for current segment
Mark out / cut end point for current segment
Label current segment
Split segment at cursor
Select previous segment
Select next segment
Reorder segments by start time
Invert all segments on timeline
Create fixed duration segments
Create num segments
Shuffle segments order
Clear all segments
Show sidebar
Edit tracks / metadata tags
Extract all tracks
Zoom in timeline
Zoom out timeline
Toggle zoom between 1x and a calculated comfortable zoom level
Export segment(s)
Capture snapshot
Delete source file
Convert current file to supported format
Batch convert files to supported format
Previous file
Next file
Close batch
Merge/concatenate files
Cut mode
Capture frame format
Keep or discard audio tracks
Change rotation
Set custom start offset/timecode
Undo
Redo
Close current screen
```

**Comment by oliko-tk** [comment]
an option to be able to export in JPG all the frames of a range or segment

**Comment by mifi** [comment]
Hi @tjdennis - unfortunately i accidentally left those keys out. I will be fixed in the next release
https://github.com/mifi/lossless-cut/commit/dfffd04b94c373373cf367651b7f484da12c1fd4

**Comment by tjdennis** [comment]
Thanks! I found the file and made the changes. Works great!

**Comment by cristianvogel** [comment]
big up to LLC ! nothing as smart as this editor anywhere around imo...

I would suggest a binding for `Fix Duration` .. because that is one of things I have to do a lot in LLC , due to other programs not closing the renders properly.

**Comment by mifi** [comment]
> I would suggest a binding for `Fix Duration` .. because that is one of things I have to do a lot in LLC , due to other programs not closing the renders properly.

Thanks for the suggestion. I added that hotkey, will be avail in the next version

**Comment by Mojavve** [comment]
Fantastic keybind update!  Made my autohotkey script completely obsolete.  Only thing missing for me are binds for changing the playback volume.  I tend to change my playback volume quite a lot and I also tend to listen to other things while editing so I like changing it in LLC rather than change my overall volume.

**Comment by mifi** [comment]
@Mojavve  good idea
- [x] I added hotkeys for volume up/down (default alt+up/down)

**Comment by mifi** [comment]
Suggested from #1045:
minimize window (currently CTRL/CMD+M) - this must be handled differently because it's a menu shortcut now...

**Comment by On-Memory** [comment]
I would suggest to add a shortcut key of **hidden software**, thanks a lot!

**Comment by On-Memory** [comment]
> Suggested from #1045: minimize window (currently CTRL/CMD+M) - this must be handled differently because it's a menu shortcut now...

I would suggest to add a shortcut key of hidden software, thanks a lot!

**Comment by jtagcat** [comment]
> * [x]  Being able to change the seek time from 1 sec or 1/60 sec by using an exponential acceleration when repeatedly pressing a key.

Could this be turned off in the settings? It's really annoying to be near (±5-10m) the desired point, and have the position jump in 30m-1h intervals or even to beginning/end.

**Comment by mifi** [comment]
@jtagcat I'm not sure I understand, why would it jump in 30m intervals. Can you let go of the keys for a second so the exponential factor can reset to 1?

**Comment by jtagcat** [comment]
@mifi letting go of the keys for a second turns it in to a second per small step.

When skipping like:

https://user-images.githubusercontent.com/38327267/167806091-21edebab-075a-4813-b931-1bc5fc1fd13a.mp4

it becomes very time-consuming and tedious.

This was done on a 2-minute video, but when working with 5-hour files, finding the right spot is hard. The second reason here is that I don't want to zoom in and out all the time.

**Comment by mifi** [comment]
Im still not sure I understand. The video you shared is not from LosslessCut as I understand. You want to turn off the exponential factor? I think you can already do that by chnaging the `Timeline keyboard seek acceleration` setting to `1`.

**Comment by mifi** [comment]
from https://github.com/mifi/lossless-cut/issues/691#issuecomment-1141151163

- Export Keyboard Shortcuts. PDF would work. In the endI usually put mine in Excel so I can keep track of the ones that I customize ;)

**Comment by mifi** [comment]
From #1170 :

I want to check where my current position actually is. By playing. If it is what I want, I have to go back to the position, inaccurate.

Separate pause and stop (jump back to where you started playing or clicked with mouse) (+ keyboard) keys. Video editors generally prefer to use the stop behavior. Some use enter/space to differentiate them.

**Comment by mifi** [comment]
From #1284 :

- [ ] Select the segment in which cursor is currently on the timeline

**Comment by freMea** [comment]
It would help a lot if kbd shortcuts were shown when hovering the buttons in the UI.

**Comment by Delerium** [comment]
I'm not sure if this should go here as a feature request or if it is a bug, but being able to map the numpad numbers to functions would be nice.  I thought we could before, but it's not working now.

**Comment by mifi** [comment]
@Delerium what happens if you try to map a numpad number? it simply doesn't detect it?

**Comment by Delerium** [comment]
Exactly that. When you press a numpad number, nothing happens.

**Comment by Delerium** [comment]
Never mind. Delete my report.  For some reason windows had turned on "Mousekeys" which redirected the numpad to mouse movement, so my issue was not with losslesscut. I'm sorry!

**Comment by mifi** [comment]
- [ ] Shortcut for centering timeline view to playhead #1492

**Comment by brunompicinini** [comment]
- [ ] A simple shortcut to show/toggle waveforms.

My workflow is that I open a file and 90% of the time have to hit the waveform button to show them.

Additionally, perhaps the app should save my preference? Meaning, if I hit to show waveform, then the next time I open any file, it should remember that.

These two additions together would be great :)

**Comment by Delerium** [comment]
I think my request may have been lost at some point from being buried under several layers of issue references, but I was wondering if this was still possible to add? ( My original post is this: https://github.com/mifi/lossless-cut/issues/1611 but was closed and referenced to https://github.com/mifi/lossless-cut/issues/604#issuecomment-1585811890 which was closed and referenced to here)

I noticed you also had referenced something similar in this thread here: https://github.com/mifi/lossless-cut/issues/254#issuecomment-589509889 but your implementation of it is still missing quite a few seek speed options that I use regularly.  

Currently for long videos I have to seek and find start/stop points in SMPlayer and then make the cuts in losslesscut separately, because the 1% of length of video is way too large, but I still need the 1 second seek for fine tuning.

**Comment by mifi** [comment]
@Delerium losslesscut now has acceleration when you hold down the seek button, does that help? meaning it will seek 1 sec by default, and if you hold it down, it will speed up the seeking exponentially.

**Comment by Delerium** [comment]
> @Delerium losslesscut now has acceleration when you hold down the seek button, does that help? meaning it will seek 1 sec by default, and if you hold it down, it will speed up the seeking exponentially.

No, because I was needing consistent speed. With acceleration, I have to keep letting go of the button, then press-hold it again, and keep repeating that in hopes I don't go too fast through the file because acceleration speeds up out of control.  Honestly not sure how useful acceleration even is because of this, and I never use it.   I was mainly just hoping to get what exists in most media players, 3 customizable speeds (like 1s, 5s, 1m, but can be set to anything) configurable to 3 hotkeys (like left/right arrow, ctrl left/right arrow, shift left/right arrow). like below:
![image](https://github.com/mifi/lossless-cut/assets/3868689/f3709077-0297-4854-9446-af9a1679f0cc)
![image](https://github.com/mifi/lossless-cut/assets/3868689/53947824-93fd-4b99-9bda-958985626b1a)

**Comment by vertigo220** [comment]
Similar to what davidp57 said (which should be an option as to whether it reverts back to 100% speed after pausing or not), a missing command is to do so manually. In addition to keys to speed up and slow down playback, it should allow a key to be assigned to toggle between 1x speed and the last set speed. For example, if it's sped up to 4x, pressing that key would slow it back down to 1x, and pressing it again would return it to 4x.

**Comment by mifi** [comment]
- [ ] Shortcut to directly change playback speed to a fixed or custom value #1865

**Comment by mifi** [comment]
Hotkeys to manipulate tracks (from #1917 #1937). Something like:

- [ ] disable all tracks
- [ ] enable all audio tracks
- [ ] enable all video tracks
- [ ] enable audio track number #N
- [ ] enable video track number #N
- [x] toggle current filter (`toggleStripCurrentFilter`)
- [x] toggle all tracks (`toggleStripAll`)
- [x] toggle `audio` tracks (`toggleStripAudio`)
- [x] toggle `video` tracks (`toggleStripVideo`)
- [x] toggle `subtitle` tracks (`toggleStripSubtitle`)
- [x] toggle `thumbnail` tracks (`toggleStripThumbnail`)
- [ ] toggle `attachment` tracks

**Comment by 7f5d3nbctkx8gcxwek9e7z3him6f44a7** [comment]
Feature request: Keyboard shortcut for confirmation actions

I'd like to propose a keyboard shortcut for confirmation actions such as "Confirm", "Execute", or "OK" buttons. This would be particularly useful for CLI operations.

Current issue:
When executing commands like:
`curl -X POST http://localhost:8080/api/action/detectSilentScenes`
or
`losslesscut.exe --keyboard-action detectSilentScenes`

The CLI execution pauses, waiting for user input on the LosslessCut GUI. This requires manual intervention to press the "Confirm" button to proceed with actions like silent detection.

Proposed solution:
Implement a keyboard shortcut or action name for these confirmation steps. This would allow for more comprehensive CLI automation and improve the overall user experience.

Use case:
- Automating workflows that involve multiple LosslessCut actions
- Enabling full CLI control without GUI interaction

This enhancement would significantly expand CLI capabilities and streamline automated processes using LosslessCut.

**Comment by 7f5d3nbctkx8gcxwek9e7z3him6f44a7** [comment]
Feature request: Keyboard shortcut for confirmation actions

I'd like to propose a keyboard shortcut for confirmation actions such as "Confirm", "Execute", or "OK" buttons. This would be particularly useful for CLI operations.

Current issue:
When executing commands like:
`curl -X POST http://localhost:8080/api/action/detectSilentScenes`
or
`losslesscut.exe --keyboard-action detectSilentScenes`

The CLI execution pauses, waiting for user input on the LosslessCut GUI. This requires manual intervention to press the "Confirm" button to proceed with actions like silent detection.

Proposed solution:
Implement a keyboard shortcut or action name for these confirmation steps. This would allow for more comprehensive CLI automation and improve the overall user experience.

Use case:
- Automating workflows that involve multiple LosslessCut actions
- Enabling full CLI control without GUI interaction

This enhancement would significantly expand CLI capabilities and streamline automated processes using LosslessCut.

**Comment by starfishpatkhoo** [comment]
> From [#1284](https://github.com/mifi/lossless-cut/issues/1284) :
> 
>     * [ ]  Select the segment in which cursor is currently on the timeline

+1 for this keyboard shortcut...

Currently I need to create multiple recap videos (and such) from a single source video. It's faster through Losslesscut. I just load the video, go through it, then press "B" to split into segments at cursor (instead of "I" and "O"). Then select/mark the ones I want, and export+merge. Then go through again and reselect different segments for a different recap video. The saved Project file also keeps a list of all segments so later I can go back and reselect different segments as needed easily.

Just that at the moment, I need to use the mouse to select/unselect individual segments, whereas all the other steps are keyboard driven. So would be great for a keyboard shortcut to select/unselect or mark/unmark the current segment. 😄

**Comment by mifi** [comment]
> +1 for this keyboard shortcut...

next version will have a new action `selectSegmentsAtCursor`

**Comment by Benniepie** [comment]
A few suggestions that I think would help with working in total seconds for timecodes or clip duration 

- [x] Toggle timecode entry/display format between HH:mm:ss.SSS and ssssss.SSS (or add a system setting)

and/or:
- [x] Allow timecode seek input in seconds & decimal secoonds and convert to HH:mm:ss.SSS on input
e.g. Modify existing shortcut G - Press G enter 71.2s  press enter time code seeks to  00:00:01:11.200
or a New Shortcut - Press S enter 71.2 press enter time code seeks to 00:00:01:11.200

- [x] Same with relative seek  (+ or - seek.) when selecting a segment to be cut the total duration in seconds can be used. 
e.g. Modify G - Press G enter +90s press enter, seek current timecode+ 00:00:01:30.000 
or New - Press S enter +7500 press enter. seek current timecode= + 00:02:05:00.000

Apologies if these are already covered somewhere else. Thanks for the app!

**Comment by mifi** [comment]
> * Toggle timecode entry/display format between HH:mm:ss.SSS and ssssss.SSS (or add a system setting)

I will add a new option "Total seconds" to the existing setting "timecode show"

> * Allow timecode seek input in seconds & decimal secoonds and convert to HH:mm:ss.SSS on input
>   e.g. Modify existing shortcut G - Press G enter 71.2s  press enter time code seeks to  00:00:01:11.200
>   or a New Shortcut - Press S enter 71.2 press enter time code seeks to 00:00:01:11.200
> * Same with relative seek  (+ or - seek.) when selecting a segment to be cut the total duration in seconds can be used.
>   e.g. Modify G - Press G enter +90s press enter, seek current timecode+ 00:00:01:30.000
>   or New - Press S enter +7500 press enter. seek current timecode= + 00:02:05:00.000

that's a great idea. i'm implementing now

**Comment by new1-test** [comment]
can you please add hotkey that moves segment input to next place?
: click onto minutes or seconds or miliseconds, input value, press hotkey to switch to next place to the right.
example: 
click onto segment start minutes place, enter value, 
press numpad * to switch to seconds place, enter value, 
press * to switch to milliseconds, enter value, 
press * to switch to segment end hour place, enter value
and so on

shift * to move backwards

it will decrease the amout of precise mouse clicks needed when creating segments.

**Comment by mifi** [comment]
> can you please add hotkey that moves segment input to next place?
> : click onto minutes or seconds or miliseconds, input value, press hotkey to switch to next place to the right.

related #1694

**Comment by mifi** [comment]
- [ ] align segment times to keyframes, individual choices #2654

**Comment by mifi** [comment]
- [ ] Bind mouse events to custom keyboard actions

**Comment by Gamba04** [comment]
Hi! I think there should be a keybind to directly reset the playback speed back to 100% without affecting play/pause, since right now the only way to do so while playing (please correct me if I'm wrong) is to pause the playback in any way and then execute `togglePlayResetSpeed`. This would be helpful because sometimes you're watching the video at a certain speed and you just want to quickly switch back to normal speed without interrupting the playback.

**Comment by mifi** [comment]
> Hi! I think there should be a keybind to directly reset the playback speed back to 100% without affecting play/pause, since right now the only way to do so while playing (please correct me if I'm wrong) is to pause the playback in any way and then execute `togglePlayResetSpeed`. This would be helpful because sometimes you're watching the video at a certain speed and you just want to quickly switch back to normal speed without interrupting the playback.

Hi, can't you use the <kbd>j</kbd> and <kbd>l</kbd> ?

**Comment by Gamba04** [comment]
> Hi, can't you use the `j` and `l` ?

So the "problem" with that is that if your playback is sped up or slowed down several times, you would have to press the key several times until you reach the default speed, and it would not be instant.

Aside from using LosslessCut to edit videos directly, I sometimes record my screen while playing a video in LosslessCut in full screen while enjoying the capabilities of arbitrarily speeding up and down or even moving frame by frame at specific parts of the video (which btw this is unrelated but I absolutely love that when I do that it doesn't show any messages or information on screen, it keeps everything clean).

So what I generally do when I have the video playing at a different speed and want to quickly reset back to normal speed while the video is playing, I just double press `space` (or `togglePlayResetSpeed`) as fast as possible so the pause is barely noticeable. I'm suggesting a dedicated keybind to instantly reset the speed without affecting play/pause.
