### ISSUE TITLE
Upgrade electron to newest

### ISSUE THREAD

**Issue by mifi** [mifi/lossless-cut#714]
This would give benefits:

- Improved performance and bugfixes in chromium/electron
- Fix crashes seen on Apple M1
- [x] can replace `open` with `shell.showItemInFolder(fullPath)` (Reveal converted file in finder/explorer) https://www.electronjs.org/docs/api/shell
- [x] replace `trash` with `shell.trashItem(path)` for (hopefully) better trash guarantee https://github.com/mifi/lossless-cut/issues/537#issuecomment-751785528
- hopefully fixes: Release file handle when opening new file #272
- [x] Native h265/hevc support https://github.com/mifi/lossless-cut/issues/88#issuecomment-1192478127

☑️ Upgrade was blocked by https://github.com/electron/electron/issues/26143 and https://github.com/libuv/libuv/issues/3050 - I tested upgrading but losslesscut becomes unbearably slow in newest versions of electron. **Now fixed!**

May have to look into https://github.com/vercel/hyper/pull/5803/files

## TODO

CSP `<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline' 'unsafe-eval';" />`

```js
app.on('ready', async () => {
  // https://github.com/electron/electron/issues/23757
  electron.protocol.registerFileProtocol('file', (request, callback) => {
    const pathname = decodeURIComponent(request.url.replace('file:///', ''));
    callback(pathname);
  });
```

update `package.json` browserlist electron version

electron-store,electron-builder,electron-builder-notarize versions have been pinned in package.json (not `^`)

we are heavy on electron.remote so probably need to use https://www.npmjs.com/package/@electron/remote

## test
- [x] test all native modules
- [x] test confirm close after upgrade to 12
- [x] test packed build and signed (MAS) `npx react-scripts build && npx electron-builder --mac`
- ...

**Comment by ryneeverett** [comment]
It might be worth noting that [electron-8x is EOL](https://www.electronjs.org/releases/stable?version=8) so there are likely unpatched security issues, for example:

- https://github.com/advisories/GHSA-hvf8-h2qh-37m9
- https://github.com/advisories/GHSA-mpjm-v997-c4h4

**Comment by mifi** [comment]
Yea. There's still a critical bug in MacOS/electron that is preventing me (and a lot of other electron apps) from upgrading to v12. Although I'd love to upgrade to 12, I'm not going to prioritise implementing a hack workaround in losslesscut until absolutely necessary.

**Comment by folknor** [comment]
The app is now no longer working on any recent linux distro without custom launch flags: https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1033855419

You might want to mention this in the release notes or in the projects readme. `./LosslessCut.AppImage --no-sandbox` works fine, for example. There's at least 2 other builtin flags that will also probably make it run, they're listed in the linked issue thread somewhere.

**Comment by mifi** [comment]
There is already a line in the readme about no-sandbox: https://github.com/mifi/lossless-cut#troubleshooting--faq
Is there anything else needed to get it to run on linux now?

**Comment by robertgzr** [comment]
electron [v20](https://www.electronjs.org/releases/stable#20.0.0) is out :rocket:

**Comment by mifi** [comment]
now upgraded to electrion 21
